### ISSUE TITLE
Layout editing priorities

### ISSUE THREAD

**Issue by warpech** [Polyjuice/Polyjuice#42]
As discussed between @Starcounter-Jack, @tomalec and me:

- [ ] 1a. Forking/version history (**offloaded** - assign to Alexey?) - https://github.com/Polyjuice/Launcher/issues/114 2b., https://github.com/Polyjuice/Launcher/issues/122, https://github.com/Polyjuice/Launcher/issues/102
- [x] 1b. Remove packery from runtime: Unbind repack from resize event [description at wiki], https://github.com/Juicy/juicy-tile-list/issues/16 (https://github.com/Polyjuice/Launcher/wiki/include-template-in-Polyjuice#how-launcher-uses-juicy-web-components-to-improve-plain-include-template-experience)
- [x] 2. Introduce fractions to ~~input~~ output  - https://github.com/Juicy/juicy-tile-grid/issues/8 - https://github.com/Polyjuice/Polyjuice/issues/6, https://github.com/Juicy/juicy-tile-grid/issues/6, [juicy-tile-grid wiki on responsiveness and fractions](https://github.com/Juicy/juicy-tile-grid/wiki/How-to-create-responsive-design-with-Juicy-elements) 
- [ ] 3. Remove packery from runtime [description at wiki](https://github.com/Polyjuice/Launcher/wiki/include-template-in-Polyjuice#how-launcher-uses-juicy-web-components-to-improve-plain-include-template-experience)
  - [x] 3.1. (min. requirement) Separate layout from repack events in life cycle - https://github.com/Juicy/juicy-tile-list/issues/28
  - [ ] 3.2. Separate Custom Elements with pure CSS config from one with packing config - https://github.com/Juicy/juicy-tile-list/issues/28, https://github.com/Polyjuice/Launcher/issues/99,  Polyjuice/Launcher#100
- [x] 4. Tight groups (Nested ShadowDOM CSS Grids) vs loose groups (subgrids/regular virtual containers/current groups) - https://github.com/Juicy/juicy-tile-grid/issues/12, [description at wiki](https://github.com/Polyjuice/Launcher/wiki/Juicy-tiles#tight--loose-groups----grid-only-construction_worker)
- [x] 5. Never generate % in output grid, comes as result of 2.
- [ ] 6. Separate layout from launcher (Layout app?) (**offloaded**)
- [ ] 7. Flexbox output

@tomalec can you match the points to existing issues?

1a and 1b are due May 20

1a and 6 will not be done Tomek

**Comment by warpech** [comment]
@tomalec will describe the changes before proceeding

**Comment by tomalec** [comment]
Here is description of Polyjuice magic around `include-template`, and separating CSS pahse from bin-packing https://github.com/Polyjuice/Launcher/wiki/include-template-in-Polyjuice

and here on juicy-tiles behavior: https://github.com/Polyjuice/Launcher/wiki/Juicy-tiles

Comments are more than welcome.

**Comment by tomalec** [comment]
Speeking on 1b. I found a reason why it does not make much sense.
Example:
We do have tiles A,B,C,D to arrange within container (group, or root container). Width of all of them is given in fractions: 

1. A: 1fr
2. B: 2fr
3. C: 1fr
4. D: 3fr

Should we then lay them out like:
```
ABBCDDD
```
as there is no rule that would stop us from putting hundreds of tiles into first row?


Therefore I would suggest use of percentages in input (JSON), and consider fractions or at least percentages as output (CSS)

**Comment by warpech** [comment]
I don't care that much about what is the unit, but to remind what is possible right now:

Percentage widths, relative to the parent:

tile 50% width of the parent | tile 50% width of the parent
-------|-------

Pixel widths, absolute:

tile 200px width | tile 200px width
-------|-------

Pixel widths and percentages combined:

tile 200px width | tile 50% width of the parent (not useful at all, because it can only work in a predictable way if the parent width is fixed)
-------|-------

The goal of introducing fractions is to be able to express:

tile 200px width | tile 50% width of the available space | tile 50% width of the available space
-------|-----|---

The sum of the above widths should be 100% width of the parent

**Comment by tomalec** [comment]
The term "available space" is the problem. On input (before packing) what would you call "the space"? During packing we need strict sizes: fixed, or at least relative to the container we are packing into.

**Comment by tomalec** [comment]
Discussion on fractions is at https://github.com/Polyjuice/Polyjuice/issues/61

**Comment by tomalec** [comment]
There is one thing worth discussion in https://github.com/Juicy/juicy-tile-grid/issues/12 
"4. Tight groups" collides with "3.2. Separate Custom Elements with pure CSS config.."

**Comment by warpech** [comment]
Closing as not relevant anymore. Layout editing priorities are now tracked in https://github.com/Starcounter/RebelsLounge/issues/32
